### PR TITLE
Fonts and UI changes

### PR DESCRIPTION
**Pull request by j-kincaid**
## PR Description 

Changed fonts and UI for Halloween theming, incorporating custom artwork
new_fonts_and_UI

### Fixes # (issue)

Issue #28 
### Describe how to test your PR locally

- Open `index.html` locally

### CODE REVIEW

**Comment by Alexandria** [comment]
Looks really good! but it is running out of the box. One you fix this we should be good to merge! 
image

**Comment by j-kincaid** [comment]
You're right! That's created the merge conflict. Yikes, I'm so glad this is a learning space because I think it was a mistake to submit 2 PRs in a row. I'm just looking at this for the first time today. Back soon.

**Comment by j-kincaid** [comment]
Time will tell, but I believe it's all good. I made the changes and the icons are staying on the board. I also changed the pathing in the app.js file so the candies aren't nested in a separate halloween directory. 

Screen Shot 2021-10-30 at 3 26 21 PM
.

**Comment by Alexandria** [comment]
@j-kincaid Okay I am still seeing this bleed through .... weird. Can you try updating from main?
image

**Comment by j-kincaid** [comment]
> @j-kincaid Okay I am still seeing this bleed through .... weird. Can you try updating from main? image

I will try again. If I cannot get this to work ultimately, thank you for being our Project Coordinator, Lex! I've learned so much! Ok. Not giving up... Let's give it a chance.

**Comment by j-kincaid** [comment]
I see the problem, on my end there is a merge conflict that started a while back. Let me see if it's possible to fix on my repo.

**Comment by j-kincaid** [comment]
It looks like it mighta worked.

**Comment by j-kincaid** [comment]
```
git push -u origin ui-updates
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 886 bytes | 886.00 KiB/s, done.
Total 6 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/j-kincaid/match-three-game
   4dbab51..e4ebffb  ui-updates -> ui-updates
Branch 'ui-updates' set up to track remote branch 'ui-updates' from 'origin'.
goldilocks@Jessicas-Air match-three-game % git remote -v
origin  https://github.com/j-kincaid/match-three-game (fetch)
origin  https://github.com/j-kincaid/match-three-game (push)
upstream        https://github.com/Alexandria/match-three-game.git (fetch)
upstream        https://github.com/Alexandria/match-three-game.git (push)
goldilocks@Jessicas-Air match-three-game % 
```

**Comment by j-kincaid** [comment]
Or should I merge the local ui-upates branch with my main and push that to the upstream main?

**Comment by j-kincaid** [comment]
@Alexandria Thank you for mentoring us during this event. It's been a valuable learning experience!

**Pull request closed without merging**
