### PR TITLE
Added cursor pointer on play button and on the candies

### LINKED ISSUE #66: No cursor pointer when hovering over the play button or hovering over the candies
**Describe the bug**
Whenever I'm hovering over the play button and hovering over the candies, I don't feel like the button is clickable or the candies are draggable.

**Expected behavior**
There should be cursor pointer on the play button and the cursor pointer should also be there when hovering over the candy to get the feel that the button is clickable and that the candies are draggable.

### PR DESCRIPTION
**Pull request by rsinghcodes**
## PR Description 

**Fixes #66** 

I've added cursor pointer on play button and on the candies so that we could get the feel that the button is clickable and the candies are draggable.

Please review it and merge it.

Thanks!!

### CODE REVIEW

**Comment by Alexandria** [comment]
Awesome can you add a screen shot of what you resolved? Thanks!

**Comment by rsinghcodes** [comment]
> Awesome can you add a screen shot of what you resolved? Thanks!

### Bug Fixed Screenshot 👇

Bug Fixed Screenshot

Bug Fixed Screenshot 1

**Review by Alexandria — APPROVED** [review]
Awesome, great job!

**Comment by rsinghcodes** [comment]
> Awesome, great job!

Thank you so much!!!! Looking forward to contribute more.

**Pull request merged**
