### PR TITLE
pause on blur, resume on focus

### LINKED ISSUE #73: Feature request : pause on page blur
**Is your feature request related to a problem? Please describe.**
There is currently no way to pause the game if the user needs to switch tab to work on something else mid game. When the user comes back to the game tab, the game is usually over. 

**Describe the solution you'd like**
Game should pause on page blur and automatically resume on focus, allowing the user to switch tabs and not lose their progress.

### PR DESCRIPTION
**Pull request by Sarahjdes**
## PR Description 

On page blur, game will pause. On page focus, game will resume. There are no indication made to the interface (ex. no pause icon or overlay), but it could be a future feature!

### Describe how to test your PR locally

- Open `index.html` locally 
- Start game
- Switch for a tab for a few seconds.
- Come back to the tab, the timer should be at the same number it was before switching tabs

### CODE REVIEW

**Review by Alexandria — APPROVED** [review]
This is a really good idea! Thanks for the contribution.

**Comment by Alexandria** [comment]
@Sarahjdes  Once you resolve the merge conflicts I will approve and merge!

**Comment by Sarahjdes** [comment]
@Alexandria We should be good now! 

Also , would you be willing to keep on maintaining this project once Hacktoberfest is over? I'd like to keep on contributing to it, I see a lof of features we could add. I don't get to develop games at work, I'd love to work on something different for fun!

**Comment by Alexandria** [comment]
> @Alexandria We should be good now!
> 
> Also , would you be willing to keep on maintaining this project once Hacktoberfest is over? I'd like to keep on contributing to it, I see a lof of features we could add. I don't get to develop games at work, I'd love to work on something different for fun!

Oh absolutely! I have every intention on keeping this game up as a resource. It will remain open source indefinitely

**Review by Alexandria — APPROVED** [review]

**Pull request merged**
